### ISSUE TITLE
Sometime it is only two page

### ISSUE THREAD

**Issue by FateLight** [Devlight/InfiniteCycleViewPager#16]
After repeated cycles

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. 
I attempt to fix this. 
Try to set another interpolation.

**Comment by lightzero** [comment]
Whether the distance between the top and the bottom can be customized？

**Comment by GIGAMOLE** [comment]
There attribute min_scale_offset.

**Comment by lightzero** [comment]
Thanks

**Comment by Ovi-nascenia** [comment]
Is that bug in developing?
