### ISSUE TITLE
scroll event not smooth, it always cause click event

### ISSUE THREAD

**Issue by TakWolf** [Devlight/InfiniteCycleViewPager#8]
Scroll event not smooth. If first time scroll success, the next scroll event always fail and cause click event. How to solve?

---

滑动事件不流畅，通常第一次滑动成功，第二次滑动的时候通常会引起点击事件，如何解决这个问题？

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
I`ll try to fix this soon.

**Comment by TakWolf** [comment]
Thank you for your repository and expect improvement !

**Comment by NaderNabil216** [comment]
i want to include the horizontal fragment inside a scrollview but it doesn't work

**Comment by GIGAMOLE** [comment]
And this i'll try to fix.

**Comment by GIGAMOLE** [comment]
Currently i don't know how to fix this. Solution will be later. As for ScrollView i didn't see any problem.
